#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export LC_ALL=en_PH.UTF-8
export LC_CTYPE=en_PH.UTF-8
export LANG=en_PH.UTF-8
export DEFAULT_USER=vulpes
LC_ALL=$LANG

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

