#!/usr/bin/env sh

killall -q polybar

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

MONITOR=$(polybar -m|tail -1|sed -e 's/:.*$//g')
BAT_ADAPTER=$(ls -1 /sys/class/power_supply/|head --lines=1)
BAT_SOURCE=$(ls -1 /sys/class/power_supply/|tail --lines=1)

xrdb -load ~/.cache/wal/colors.Xresources
polybar -l "info" --config=$1 $2 &> polybar.log &

#https://www.reddit.com/r/i3wm/comments/6lo0z0/how_to_use_polybar/djvp7ok/
