#!/bin/bash

getXCol () {
#	echo	$(xrdb -query |
#			grep "*color$1:.*#" |
#			cut -d"#" -f2)
	echo $(sed "$(($1+1))q;d" $HOME/.cache/wal/colors)
}

BG="$(getXCol 0)"
FG="$(getXCol 15)"

CRIT="$(getXCol 9)"
NORM="$(getXCol 2)"
LOW="$(getXCol 2)"

killall dunst
dunst \
	-lb "$BG" -nb "$BG" -cb "$BG" \
	-lf "$FG" -nf "$FG" -cf "$FG" \
	-lfr "$LOW" -nfr "$NORM" -cfr "$CRIT" &
#dunst &
