#!/usr/bin/env sh

killall -q polybar

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

MONITOR=$(polybar -m|tail -1|sed -e 's/:.*$//g')

xrdb -load ~/.cache/wal/colors.Xresources
polybar -l "info" --config=$1 $2 &

#https://www.reddit.com/r/i3wm/comments/6lo0z0/how_to_use_polybar/djvp7ok/
