#!/bin/bash

getXCol () {
#	echo	$(xrdb -query |
#			grep "*color$1:.*#" |
#			cut -d"#" -f2)
	echo $(sed "$(($1+1))q;d" $HOME/.cache/wal/colors | cut -d"#" -f2)
}

CMARGIN=200
BGCOL=$(getXCol 0)
TRANS="FF"
MAINCOL=$(getXCol 2)$TRANS
SECCOL=$(getXCol 15)$TRANS
URGCOL=$(getXCol 9)$TRANS
FONT="eurofurence"
ICOFONT="Font Awesome 5 Free:style=Solid"
TIMESIZE=75
DATESIZE=$((($TIMESIZE / 5) * 3))

i3lock\
	--force-clock\
	-s\
	-c $BGCOL\
	-e\
	--composite\
	--radius=100\
	--ring-width=20\
	--time-font="$FONT"\
	--timesize=$TIMESIZE\
	--timestr="%H:%M"\
	--timepos="x+w-$CMARGIN:y+h-$CMARGIN"\
	--time-align 2\
	--timecolor="$MAINCOL"\
	--date-font="$FONT"\
	--datesize=$DATESIZE\
	--datestr="%a, %e %b %Y"\
	--datepos="x+$CMARGIN:ty"\
	--date-align 1\
	--datecolor="$MAINCOL"\
	--verifpos="w/2:h/2+15"\
	--verif-align=0\
	--verifcolor="$URGCOL"\
	--verif-font="$ICOFONT"\
	--verifsize=40\
	--veriftext=""\
	--wrongpos="w/2:h/2+15"\
	--wrong-align=0\
	--wrongcolor="$URGCOL"\
	--wrong-font="$ICOFONT"\
	--wrongsize=40\
	--wrongtext=""\
	--noinputtext="-"\
	--separatorcolor="$BGCOL$TRANS"\
	--keyhlcolor="$SECCOL"\
	--bshlcolor="$URGCOL"\
	--ringcolor="$MAINCOL"\
	--ringvercolor="$URGCOL"\
	--ringwrongcolor="$URGCOL"\
	--insidecolor="00000000"\
	--insidevercolor="00000000"\
	--insidewrongcolor="00000000"
