#!/bin/bash

getXCol () {
	echo	$(xrdb -query |
			grep "*color$1:.*#" |
			cut -d"#" -f2)
}

CMARGIN=100
BGCOL=$(getXCol 0)
TRANS="FF"
MAINCOL=$(getXCol 2)$TRANS
SECCOL=$(getXCol 15)$TRANS
URGCOL=$(getXCol 9)$TRANS
FONT="Source Sans Pro Light"
TIMESIZE=75
DATESIZE=$((($TIMESIZE / 5) * 3))

i3lock\
	-k\
	--composite\
	-s\
	-c $BGCOL\
	--timefont="$FONT"\
	--timesize=$TIMESIZE\
	--timestr="%H:%M"\
	--timepos="x+w-cw-$CMARGIN:y+h-(ch/2)-$CMARGIN"\
	--time-align 2\
	--timecolor=$MAINCOL\
	--datefont="$FONT"\
	--datesize=$DATESIZE\
	--datestr="%a, %e %b %Y"\
	--datepos="x+$CMARGIN:ty"\
	--date-align 1\
	--datecolor=$MAINCOL\
	--veriftext=""\
	--wrongtext=""\
	--statusfont="FontAwesome"\
	--textsize=40\
	--radius=60\
	--ring-width=20\
	--textcolor=$URGCOL\
	--separatorcolor=$BGCOL$TRANS\
	--keyhlcolor=$SECCOL\
	--bshlcolor=$URGCOL\
	--ringcolor=$MAINCOL\
	--ringvercolor=$URGCOL\
	--ringwrongcolor=$URGCOL\
	--insidecolor="00000000"\
	--insidevercolor="00000000"\
	--insidewrongcolor="00000000"
