#!/bin/bash

getXCol () {
#	echo	$(xrdb -query |
#			grep "*color$1:.*#" |
#			cut -d"#" -f2)
	echo $(sed "$(($1+1))q;d" $HOME/.cache/wal/colors)
}

CMARGIN=100
BGCOL=$(getXCol 0)
TRANS="FF"
MAINCOL=$(getXCol 2)$TRANS
SECCOL=$(getXCol 15)$TRANS
URGCOL=$(getXCol 9)$TRANS
FONT="Source Sans Pro Light"
TIMESIZE=75
DATESIZE=$((($TIMESIZE / 5) * 3))

i3lock\
	--force-clock\
	-s\
	-c $BGCOL\
	-e\
	--composite\
	--time-font="$FONT"\
	--timesize=$TIMESIZE\
	--timestr="%H:%M"\
	--timepos="x+w-$CMARGIN:y+h-$CMARGIN"\
	--time-align 2\
	--timecolor=$MAINCOL\
	--date-font="$FONT"\
	--datesize=$DATESIZE\
	--datestr="%a, %e %b %Y"\
	--datepos="x+$CMARGIN:ty"\
	--date-align 1\
	--datecolor=$MAINCOL\
	--veriftext=""\
	--wrongtext=""\
	--verifsize=40\
	--wrongsize=40\
	--radius=60\
	--ring-width=20\
	--verifcolor=$URGCOL\
	--wrongcolor=$URGCOL\
	--separatorcolor=$BGCOL$TRANS\
	--keyhlcolor=$SECCOL\
	--bshlcolor=$URGCOL\
	--ringcolor=$MAINCOL\
	--ringvercolor=$URGCOL\
	--ringwrongcolor=$URGCOL\
	--insidecolor="00000000"\
	--insidevercolor="00000000"\
	--insidewrongcolor="00000000"
