#!/bin/sh

end() {
	echo "Quitting."
	
	kill $FFMPEG_PID
	kill $YOUTUBEDL_PID

	[ -z "$TEMP_DIR" ] || rm -rf "$TEMP_DIR"
}

trap end INT TERM EXIT

echo "Getting playlist $1"
IDS="$(youtube-dl --flat-playlist -j $1 | jq -r .id)"

echo "$IDS" | while read -r line || [[ -n "$line" ]]; do
	echo "Getting $line"
	TEMP_DIR="$(mktemp -d /tmp/play_list.XXXXXXXXX)"
	TEMP_FIFO="$TEMP_DIR/aac"

	mkfifo "$TEMP_FIFO" || exit 1

	sh -c "cat $TEMP_FIFO | ffmpeg -nostats -i - -f s16le -acodec pcm_s16le -ac 2 -ar 48000 - | aplay -f dat" &
	FFMPEG_PID=$!

	youtube-dl -f140 "$line" -o - > "$TEMP_FIFO"
	YOUTUBEDL_PID=$!

	wait $YOUTUBEDL_PID
	kill $FFMPEG_PID

	rm -rf "$TEMP_DIR"
done 
