#!/bin/sh
notify-send "reflector" "Updating mirrorlist..."
sudo reflector --verbose -l 100 -f 50 --sort rate -p http -p ftp --threads 2 --save /etc/pacman.d/mirrorlist
notify-send "reflector" "mirrorlist updated."
