#!/bin/bash
#rofi -font 'Source Code Pro Semibold 13' -show drun -modi 'drun,run' -sidebar-mode -theme-str "#window {location:north;y-offset:25;padding:3px;}"
#rofi -font 'Source Code Pro Semibold 13' -show drun -modi 'drun,run' -sidebar-mode -theme ~/.cache/wal/colors-rofi-light.rasi
rofi -font 'Source Code Pro Semibold 13' -show drun -theme ~/.cache/wal/colors-rofi-dark.rasi -sort -levenshtein-sort -show-icons -scroll-method 1
