#!/bin/bash
#rofi -font 'Source Code Pro Semibold 13' -show window -theme-str "#window {location:north;y-offset:25;padding:3px;}"
rofi -font 'Source Code Pro Semibold 13' -show window -theme ~/.cache/wal/colors-rofi-dark.rasi -sort -levenshtein-sort -show-icons -scroll-method 1\
	-window-format "[{w:1}] {t:30}"
