#!/bin/bash

#DIRECTORY = $(zenity --file-selection --save)
#scrot -d 1 -s -q 100 '%d-%b-%y_%T.png' -e 'mv $f $DIRECTORY' && \
#sleep 1 && \

scrot -d 1 -s -q 100 'scrot.png' \
	-e 'xclip -selection clipboard -t image/png $f && \
	mv $f ~/.cache' && \
file="$(zenity --file-selection --save)" && \
mv "$HOME/.cache/scrot.png" "$file" && \
notify-send -t 3000 -u low "Screenshot taken." "$file"
