#!/bin/bash

#unsplash-wallpaper -f \
#	-q skyline,sunset \
#	-d $HOME/CommonFiles/Wallpapers/Unsplashed \
#	--width 1920 \
#	--height 1080

SEARCH=${1:-"skyline sunset"}
SEARCH=${SEARCH// /%2C}

RES=${2:-"1920x1080"}

WALLPAPERPATH=$HOME/Wallpapers
WALLPAPER=$WALLPAPERPATH/current_wallpaper.png

if [ -f $WALLPAPER ]; then
	rm $WALLPAPER
fi
if [ ! -d $WALLPAPERPATH ]; then
	mkdir $WALLPAPERPATH
fi
wget "https://source.unsplash.com/random/$RES/?$SEARCH" \
	-O $WALLPAPER
nitrogen --set-zoom-fill $WALLPAPER --save
bash $HOME/scripts/setcolorscheme
