#!/bin/sh
#sudo create_ap\
#	--freq-band 2.4\
#	--dhcp-dns 8.8.8.8,8.8.4.4\
#	-m nat\
#	-c 3\
#	--ieee80211ac\
#	--ieee80211n\
#	wlp4s0 wlp4s0 xyzzy nanobot321

sudo create_ap\
	--freq-band 2.4\
	-m nat\
	--dhcp-dns 8.8.8.8,8.8.4.4\
	--ieee80211ac\
	-c 4\
	--isolate-clients\
	wlp4s0 wlp4s0 xyzzy nanobot321
